proxy:
  title: ShinyProxy
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
      #url: http://localhost:2375
  specs:
  - id: 01_basic_app
    display-name: Shiny Basic App
    description: A basic app
    container-cmd: ["R", "-e", "shiny::runApp(port=3838, host='0.0.0.0')"]
    container-image: corey/basic_shiny
    container-network: shiny_net
    access-groups: [admins]

logging:
  file:
    /log/shinyproxy.log